export const SEARCH_FILTER = {
  開発言語: [
    "Java",
    "PHP",
    "Python",
    "Ruby",
    "Go言語",
    "Scala",
    "Perl",
    "JavaScript",
    "HTML",
    "Swift",
    "Objective-C",
    "Kotlin",
    "Unity",
    "Cocos2d-x",
    "C言語",
    "C#",
    "C++",
    "VC++",
    "C#.NET",
    "VB.NET",
    "VB",
    "VBA",
    "SQL",
    "PL/SQL",
    "R言語",
    "COBOL",
    "Apex",
    "ASP.NET",
    "TypeScript",
    "Stylus",
    "ESLint",
    "Vuex",
    "Rust",
    "Dart",
  ],
  フレームワーク: [
    "Node.js",
    "CakePHP",
    "Ruby on Rails",
    "Spring",
    "Django",
    "FuelPHP",
    "Struts",
    "Catalyst",
    "Spark",
    "CodeIgniter",
    "Symfony",
    "Zend Framework",
    "Flask",
    "Pyramid",
    "Kohana",
    "CherryPy",
    "Seasar2",
    "Backbone.js",
    "Knockout.js",
    "AngularJS",
    "Laravel",
    "SAStruts",
    "React",
    "Vue.js",
    "Phalcon",
    "ReactNative",
    "SpringBoot",
    "Slim",
    "Yii",
    "Ethna",
    "Tornado",
    "Ember.js",
    "Flutter",
    ".NET Core",
    "Bulma",
    "NuxtJS",
    "RSpec",
    "Grails",
    "Flight",
    "Swing",
    "Next.js",
    "FastAPI",
  ],
  インフラ系: [
    "AWS",
    "Linux",
    "WindowsServer",
    "UNIX",
    "Azure",
    "Oracle",
    "Google Cloud Platform",
    "Kubernetes",
    "Fargate",
  ],
  デザイン系: [
    "Photoshop",
    "Illustrat",
    "Sketch",
    "Figma",
    "Adobe XD",
    "Maya",
    "After Eff",
    "Adobe Pre",
    "Flash",
    "SAI",
    "CLIP STUD",
    "Blender",
    "3ds Max",
    "IoT / AI",
    "データ領",
    "ゲームエ",
    "デスクト",
    "DB系開発/",
    "汎用機開",
    "制御/組み",
  ],
  その他: [
    "SAP",
    "Salesforce",
    "Abstract",
    "Mackerel",
    "CodePipeline",
    "SageMaker",
    "Fluentd",
    "CodeDeploy",
    "Cisco",
    "Tensorflow",
    "Keras",
    "Pytorch",
    "NumPy",
    "Hibernate",
    "PowerShell",
    "Active Directory",
    "ファイヤーウォール",
    "Company",
    "Exchange",
  ],
  職種: [
    "フロントエンドエンジニア",
    "フルスタックエンジニア",
    "iOSアプリ",
    "Androidアプリ",
    "クロスプラットフォームアプリ",
    "クラウドエンジニア",
    "ネットワークエンジニア",
    "DBA",
    "DevOps/SRE",
    "セキュリティエンジニア",
    "PM / PMO",
    "ITコンサル",
    "業務コンサル",
    "ERPコンサル",
    "データ領域上流",
    "システム導入支援",
    "Webディレクター",
    "マーケター",
    "ライター",
    "映像 / 動画制作",
    "マークアップ / コーダー",
    "UI / UX",
    "Webデザイナー",
    "デザイナー",
    "テストエンジニア",
    "テスター",
    "社内SE",
    "システムオペレーション",
    "テクサポ / ヘルプデスク",
    "SEサポート",
    "IT事務",
    "エンジニアリングマネージャー",
    "クラウドエンジニア",
    "バックエンドエンジニア",
    "アプリエンジニア",
    "ネットワークエンジニア",
    "iOSエンジニア",
    "汎用機エンジニア",
    "フロントエンドエンジニア",
    "AIエンジニア(人工知能)",
    "インフラエンジニア",
    "機械学習エンジニア",
    "Androidエンジニア",
    "サーバーエンジニア",
    "ブロックチェーンエンジニア",
    "データベースエンジニア",
    "セキュリティエンジニア",
    "PdM(プロダクトマネージャー)",
    "PM (プロジェクトマネージャー)",
    "PMO",
    "3Dデザイナー",
    "Webデザイナー",
    "UI・UXデザイナー",
    "2Dデザイナー",
    "キャラクターデザイナー",
    "イラストレーター",
    "マーケター",
    "VPoE",
    "CRE (Customer Reliability Engineer)",
    "SRE",
    "コンサルタント",
    "データサイエンティスト",
    "アートディレクター",
    "プランナー",
    "テスター・デバッガー・QA",
    "プロデューサー",
    "テクニカルサポート",
    "組み込み・制御",
    "ITコンサルタント",
    "データサイエンティスト",
    "ネットワークエンジニア",
    "インフラエンジニア",
    "フロントエンドエンジニア",
    "アプリケーションエンジニア",
    "セキュリティエンジニア",
    "データベースエンジニア",
    "組込・制御エンジニア",
    "汎用系エンジニア",
    "社内SE",
    "PM / PMO",
    "PL",
    "2Dデザイナー",
    "3Dデザイナー",
    "DTPデザイナー",
    "UI・UXデザイナー",
    "Webデザイナー",
    "プロダクトデザイナー",
    "HTMLコーダー",
    "アニメーター",
    "グラフィックデザイナー",
    "クリエイティブディレクター",
    "ゲームディレクター",
    "Webディレクター",
    "アートディレクター",
    "テストエンジニア",
    "テクニカルサポート",
    "デバッカー",
    "ゲームプランナー",
    "イラストレーター",
  ],
  業界: [
    "SI・業務系",
    "通信",
    "銀行・証券・保険",
    "ゲーム",
    "WEBサービス",
    "EC",
    "エンタメ",
    "広告",
    "メーカー",
    "流通・小売",
    "公共・官公庁",
    "医療・福祉",
    "その他",
  ],
  特徴: [
    "フルリモート",
    "原則リモート",
    "一部リモート",
    "常駐",
    "オンサイト",
    "時短",
    "商談1回",
    "即日参画OK",
    "スタートアップ",
    "上場企業",
  ],
  稼働日数: ["週5日", "週4日", "週3日", "週2日", "週1日"],
};
