name: Dev Build and Deploy

on:
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Dev / Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: npm

      - name: npm install
        run: npm install

      - name: ESLint
        run: npm run lint

      - name: Type Check
        run: npm run ts:test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          echo "NEXT_PUBLIC_HASURA_KEY=${{ secrets.NEXT_PUBLIC_HASURA_KEY }}" >> .env.development
          echo "NEXT_PUBLIC_HASURA_URL=${{ secrets.NEXT_PUBLIC_HASURA_URL }}" >> .env.development
          echo "AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}" >> .env.development
          echo "DEV_AUTH0_BASE_URL=${{ secrets.DEV_AUTH0_BASE_URL }}" >> .env.development
          echo "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" >> .env.development
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env.development
          echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> .env.development
          npm run deploy

        env:
          NEXT_PUBLIC_HASURA_KEY: ${{ secrets.NEXT_PUBLIC_HASURA_KEY }}
          NEXT_PUBLIC_HASURA_URL: ${{ secrets.NEXT_PUBLIC_HASURA_URL }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          DEV_AUTH0_BASE_URL: ${{ secrets.DEV_AUTH0_BASE_URL }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
